### PR TITLE
Adding DatasetDownload to Schema.org export

### PR DESCRIPTION
**Pull request by adamml**
With reference to https://github.com/opengeospatial/netcdf-ld/issues/34

### CODE REVIEW

**Comment by adamml** [comment]
Build is now passing.

I have added a file `/lib/distribution.py` with an `Enum` for the MIME-TYPE and for the Linked Data Resource we are using to define NetCDF.

There is a new class in `__init__.py`, `SchemaOrg` with currently one method `distribution` which will output that piece of the graph. This should now be called from the relevant part of `nc2rdf.py` but requires a but more testing. @jyucsiro or @marqh could you verify it's working and I'll look to add a test? My setup has gone very flaky for some reason.

**Comment by jyucsiro** [comment]
https://github.com/adamml/bald/pull/1

**Comment by marqh** [comment]
https://github.com/adamml/bald/pull/2
proposed addition of an integration test to exercise this code

**Comment by adamml** [comment]
Hi @marqh Thank you very much for all your help. I think this is good to (squash and) merge now.

**Pull request merged**
