### PR TITLE
Adding ereefs example with ncld annotations to a branch

### PR DESCRIPTION
**Pull request by jyucsiro**
This adds an example from ereefs. Some variables have attributes that use ereefs LD conventions. An alias list is created to reflect this.

### CODE REVIEW

**Comment by marqh** [comment]
Hi @jyucsiro 

please see #14 for added testing

mark

**Comment by jyucsiro** [comment]
Hmm, the problem is still with the qudt URIs not resolving/behaving properly. http://qudt.org/vocab/unit#Meter redirects to http://qudt.org/vocab/unit/#Meter and returns a HTTP Status 403 error at the moment :(

**Comment by jyucsiro** [comment]
Have updated the test case to switch from assertTrue to assertFalse (to accomodate expected error). CI checks passing now. Ready to merge PR.

**Comment by jyucsiro** [comment]
[Initial set of CDL examples](https://trello.com/c/Qo5wuwqG/23-initial-set-of-cdl-examples)

**Pull request merged**
